---
title: "Mental Health Effect on Heart Disease "
author: "Group_3 Dustin Riles, Nina Ebensperger"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: yes
    always_allow_html: true
    toc: yes
    toc_depth: 3
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '3'
  pdf_document:
    toc: yes
    toc_depth: '3'
    urlcolor: blue
---
According to the CDC, the leading cause of death in the US is heart disease(source). Heart Disease is closely aligned to personal key indicators. Indicators like physical activity, alcohol usage, and smoking can have an impact on someone's chances of developing heart disease. 

```{r init, include=F}
# Housekeeping
#rm(list = ls())


# Packages needed
#tinytex::install_tinytex()
#install.packages("dplyr")      
#install.packages("plyr")       
#install.packages("readr")   
#installed.packages('skimr', repos = "http://cran.us.r-project.org")
#install.packages
#install.packages("panelr")
#install.packages("lubridate")
#install.packages("eeptools")
#install.packages('xtable')
#install.packages('plm')
#install.packages('tseries')
#install.packages('dynlm')
#install.packages('vars')
#install.packages('broom')
#install.packages('stargazer')
#install.packages('lmtests')
#install.packages("kableExtra")
#install.packages('plotly')
#install.packages('GGally')
#install.packages('gplots')
#install.packages('ggpubr')
#install.packages('rstatix') 
library(rstatix)
library(ggpubr)
library(plotly)
library(kableExtra)
library(skimr)
library(panelr)
library(knitr)
library(stargazer)
library(dplyr)
library(readr)
library(lubridate)
library(xtable)
library(plm) 
library(corrplot)
library(tidyverse)
library(tseries) # for `adf.test()`
library(dynlm) #for function `dynlm()`
library(vars) # for function `VAR()`
library(lmtest) #for `coeftest()` and `bptest()`.
library(broom) #for `glance(`) and `tidy()`
library(ezids)
library(plot3D)
library(tinytex)
library(GGally, quietly = TRUE)
library(gplots)
library(gganimate)
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	results = "hide"
)

options(scientific=T, digits = 3) 
```

```{r setup, include=FALSE}
setwd('/Users/admin/Documents/GitHub/6101_Project/')

df = data.frame(read.csv('/Users/admin/Documents/GitHub/6101_Project/heart_2020_cleaned.csv'))

lapply(df,function(x) { length(which(is.na(x)))})
```

```{r init_data}
# Replace No for Heart Disease with 0
df$HeartDisease[df$HeartDisease == "No"] <- 0
# Replace Yes for Heart Disease with 1
df$HeartDisease[df$HeartDisease == "Yes"] <- 1
# Convert Heart Disease to factor variable
df$HeartDisease <- as.factor(df$HeartDisease)
table(df$HeartDisease)

# Replace No for Smoking with 0
df$Smoking[df$Smoking == "No"] <- 0
# Replace Yes for Smoking with 1
df$Smoking[df$Smoking == "Yes"] <- 1
# Convert Smoking to factor variable
df$Smoking <- as.factor(df$Smoking)
table(df$Smoking)

# Replace No for Alcohol Drinking with 0
df$AlcoholDrinking[df$AlcoholDrinking == "No"] <- 0
# Replace Yes for Alcohol Drinking with 1
df$AlcoholDrinking[df$AlcoholDrinking == "Yes"] <- 1
# Convert Alcohol Drinking to factor variable
df$AlcoholDrinking <- as.factor(df$AlcoholDrinking)
table(df$AlcoholDrinking)

# Replace No for Stroke with 0
df$Stroke[df$Stroke == "No"] <- 0
# Replace Yes for Stroke with 1
df$Stroke[df$Stroke == "Yes"] <- 1
# Convert Stroke to factor variable
df$Stroke <- as.factor(df$Stroke)
table(df$Stroke)

# Replace No for DiffWalking with 0
df$DiffWalking[df$DiffWalking == "No"] <- 0
# Replace Yes for DiffWalking with 1
df$DiffWalking[df$DiffWalking == "Yes"] <- 1
# Convert DiffWalking to factor variable
df$DiffWalking <- as.factor(df$DiffWalking)
table(df$DiffWalking)

# Replace Male for Sex with 0
df$Sex[df$Sex == "Male"] <- 0
# Replace Female for Sex with 1
df$Sex[df$Sex == "Female"] <- 1
# Convert Sex to factor variable
df$Sex <- as.factor(df$Sex)
table(df$Sex)

# Replace No for Physical Activity with 0
df$PhysicalActivity[df$PhysicalActivity == "No"] <- 0
# Replace Yes for Physical Activity with 1
df$PhysicalActivity[df$PhysicalActivity == "Yes"] <- 1
# Convert Physical Activity to factor variable
df$PhysicalActivity <- as.factor(df$PhysicalActivity)
table(df$PhysicalActivity)

# Replace No for Asthma with 0
df$Asthma[df$Asthma == "No"] <- 0
# Replace Yes for Asthma with 1
df$Asthma[df$Asthma == "Yes"] <- 1
# Convert Asthma to factor variable
df$Asthma <- as.factor(df$Asthma)
table(df$Asthma)

# Replace No for Kidney Disease with 0
df$KidneyDisease[df$KidneyDisease == "No"] <- 0
# Replace Yes for Kidney Disease with 1
df$KidneyDisease[df$KidneyDisease == "Yes"] <- 1
# Convert Kidney Disease to factor variable
df$KidneyDisease <- as.factor(df$KidneyDisease)
table(df$KidneyDisease)

# Replace No for Skin Cancer with 0
df$SkinCancer[df$SkinCancer == "No"] <- 0
# Repalce Yes for Skin Cancer with 1
df$SkinCancer[df$SkinCancer == "Yes"] <- 1
# Convert Skin Cancer to factor variable
df$SkinCancer <- as.factor(df$SkinCancer)
table(df$SkinCancer)

# Replace Poor for GenHealth with 0
df$GenHealth[df$GenHealth == "Poor"] <- 0
# Replace Fair for GenHealth with 1
df$GenHealth[df$GenHealth == "Fair"] <- 1
# Replace Good for GenHealth with 2
df$GenHealth[df$GenHealth == "Good"] <- 2
# Replace Very Good for GenHealth with 3
df$GenHealth[df$GenHealth == "Very good"] <- 3
# Replace Excellent for GenHealth with 4
df$GenHealth[df$GenHealth == "Excellent"] <- 4
# Convert GenHealth to factor variable
df$GenHealth <- as.factor(df$GenHealth)
table(df$GenHealth)
```

```{r, results='markup'}

#EDA

#Define the range for the skew 
#histogram 

Heart_Disease <- subset(df, HeartDisease ==1) 
print(Heart_Disease)
no_heart_disease <- subset(df, HeartDisease ==0)
print(no_heart_disease)

# Mental Health for heart_disease
heart_disease_df_mental_health_1 <- ggplot(Heart_Disease, aes(x=MentalHealth)) + 
 geom_histogram(aes(y=..density..), colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666") +
  labs(title = "Mental Health for people with Heart Disease")+
  geom_vline(data=Heart_Disease, aes(xintercept=mean(MentalHealth),color="red"),
             linetype="dashed")
heart_disease_df_mental_health_1

#Mental health without Heart Disease

no_heart_disease_df_mental_health_1 <- ggplot(no_heart_disease, aes(x=MentalHealth)) + 
 geom_histogram(aes(y=..density..), colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666") +
  labs(title = "Mental Health for people without Heart Disease") +
  geom_vline(data=no_heart_disease, aes(xintercept=mean(MentalHealth), color="red"),
             linetype="dashed")
no_heart_disease_df_mental_health_1

#Physical health without Heart Disease

no_heart_disease_df_PhysicalHealth_ <- ggplot(no_heart_disease, aes(x=PhysicalHealth)) + 
 geom_histogram(aes(y=..density..), colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666") +
  labs(title = "Smoking for people without Heart Disease") +
  geom_vline(data=no_heart_disease, aes(xintercept=mean(PhysicalHealth), color="red"),
             linetype="dashed")
no_heart_disease_df_PhysicalHealth_

#Physical health with Heart Disease

heart_disease_df_PhysicalHealth_ <- ggplot(Heart_Disease, aes(x=PhysicalHealth)) + 
 geom_histogram(aes(y=..density..), colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666") +
  labs(title = "Smoking for people without Heart Disease") +
  geom_vline(data=Heart_Disease, aes(xintercept=mean(PhysicalHealth), color="red"),
             linetype="dashed")
heart_disease_df_PhysicalHealth_



ggplot(df, aes(x=MentalHealth, y=Smoking)) + 
  geom_boxplot( colour=c("#ff0000","#11cc11"), outlier.shape=8, outlier.size=4) +
  labs(title="Mental Health ranking on Smoking Habit", x="MentalHealth", y = "Smoking")



p<-ggplot(df, aes(x=Smoking, y=HeartDisease, color=Smoking)) +
  geom_bar(stat="identity", fill="white") +
  labs(title="Smoking Habit on Heart Disease", x="Smoking", y = "Heart Disease")+
  scale_color_brewer(palette="Dark2") 
  #+ scale_x_discrete(limits=c("No", "Yes")) not working for some reason 
p

#  frequency each combination occurs for smoking and heart disease 
df %>% 
  group_by(Smoking, HeartDisease) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

#  frequency each combination occurs for stroke and heart disease 
ggplot(df, aes(x=MentalHealth, y=Stroke)) + 
  geom_boxplot( colour=c("#ff0000","#11cc11"), outlier.shape=8, outlier.size=4) +
  labs(title="Mental Health ranking on Stroke", x="MentalHealth", y = "Stroke")



p2<-ggplot(df, aes(x=Stroke, y=HeartDisease, color=Stroke)) +
  geom_bar(stat="identity", fill="white") +
  labs(title="Prevously Having a Stroke on Heart Disease", x="Stroke", y = "Heart Disease")+
  scale_color_brewer(palette="Dark2") 
  #+ scale_x_discrete(limits=c("No", "Yes")) not working for some reason 
p2


df %>% 
  group_by(Stroke, HeartDisease) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

#  frequency each combination occurs for Difficulty Walking and heart disease 
ggplot(df, aes(x=MentalHealth, y=DiffWalking)) + 
  geom_boxplot( colour=c("#ff0000","#11cc11"), outlier.shape=8, outlier.size=4) +
  labs(title="Mental Health ranking on Stroke", x="MentalHealth", y = "Difficulty Walking")



p3<-ggplot(df, aes(x=DiffWalking, y=HeartDisease, color=DiffWalking)) +
  geom_bar(stat="identity", fill="white") +
  labs(title="Difficulty Walking on Heart Disease", x="Difficulty Walking", y = "Heart Disease")+
  scale_color_brewer(palette="Dark2") 
  #+ scale_x_discrete(limits=c("No", "Yes")) not working for some reason 
p3

df %>% 
  group_by(DiffWalking, HeartDisease) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

#  frequency each combination occurs for Alcohol drinking and heart disease 
ggplot(df, aes(x=MentalHealth, y=AlcoholDrinking)) + 
  geom_boxplot( colour=c("#ff0000","#11cc11"), outlier.shape=8, outlier.size=4) +
  labs(title="Mental Health ranking on Alcohol", x="MentalHealth", y = "Alcohol")



p4<-ggplot(df, aes(x=AlcoholDrinking, y=HeartDisease, color=AlcoholDrinking)) +
  geom_bar(stat="identity", fill="white") +
  labs(title="Alcohol Consumption on Heart Disease", x="Alcohol", y = "Heart Disease")+
  scale_color_brewer(palette="Dark2") 
  #+ scale_x_discrete(limits=c("No", "Yes")) not working for some reason 
p4
df %>% 
  group_by(AlcoholDrinking, HeartDisease) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))


#  frequency each combination occurs for diabetic and heart disease 

df %>% 
  group_by(Diabetic, HeartDisease) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))


#  frequency each combination occurs for Physical Activity and heart disease 
ggplot(df, aes(x=MentalHealth, y=PhysicalActivity)) + 
  geom_boxplot( colour=c("#ff0000","#11cc11"), outlier.shape=8, outlier.size=4) +
  labs(title="Mental Health ranking on Physical Ativity", x="MentalHealth", y = "Physical Activity")



p5<-ggplot(df, aes(x=PhysicalActivity, y=HeartDisease, color=PhysicalActivity)) +
  geom_bar(stat="identity", fill="white") +
  labs(title="Physical Activity on Heart Disease", x="Alcohol", y = "Heart Disease")+
  scale_color_brewer(palette="Dark2") 
  #+ scale_x_discrete(limits=c("No", "Yes")) not working for some reason 
p5
df %>% 
  group_by(PhysicalActivity, HeartDisease) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

#  frequency each combination occurs for Asthma and heart disease 

df %>% 
  group_by(Asthma, HeartDisease) %>%
  summarise(n = n()) %>%
  mutate(freq = n / sum(n))

```

```{r}
df1 = subset(df, select = c("BMI", "PhysicalHealth", "MentalHealth", "SleepTime"))

dfcor = cor(df1)

dfcor
library(ezids)
library(tidyverse)

loadPkg("corrplot")

corrplot(dfcor, method = 'number')

```
```{r}
table(df$HeartDisease)
model1 <- glm(HeartDisease~MentalHealth + BMI + GenHealth, data = df, family = "binomial")
summary(model1)
```
